#!/usr/bin/env bash
#
# Post-`tauri android init` patches for the Android build. `gen/android`
# is gitignored and regenerated by `tauri android init`, so these MUST
# run AFTER init and BEFORE `tauri android build`. Idempotent. Invoked
# from publish.yml, engine-ci.yml, and the Makefile `android-init` target.
#
# Two patches:
#
# 1) Loopback cleartext for the in-process engine.
#    The mobile build links ps5upload-engine in-process and binds it to
#    http://127.0.0.1:19113; the renderer fetches that URL like the
#    desktop sidecar (engine_mobile.rs + client/src/api/engine.ts). Tauri
#    sets android:usesCleartextTraffic=true for debug but FALSE for
#    release, so a release APK silently blocks the loopback fetch and the
#    UI shows the engine "red". We add a network-security-config that
#    permits cleartext ONLY for 127.0.0.1 / localhost; everything else
#    stays cleartext-forbidden. networkSecurityConfig takes precedence
#    over the usesCleartextTraffic flag for those domains.
#
# 2) Explicit backup rules so user settings survive an uninstall/reinstall
#    (cloud backup / device transfer). Settings already persist across
#    normal restarts (app-private config dir) and in-place updates (now
#    that releases share a stable signing key), but allowBackup + explicit
#    include rules let Android restore them on a fresh reinstall too.

set -euo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
gen="$root/client/src-tauri/gen/android/app/src/main"
manifest="$gen/AndroidManifest.xml"
xmldir="$gen/res/xml"

if [ ! -f "$manifest" ]; then
  echo "::error::AndroidManifest.xml not found at $manifest — run 'tauri android init' first" >&2
  exit 1
fi

mkdir -p "$xmldir"

# --- (1) loopback-only cleartext --------------------------------------
cat >"$xmldir/network_security_config.xml" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<!-- Loopback-only cleartext: the in-process ps5upload-engine binds
     127.0.0.1:19113 and the WebView fetches it over plain HTTP. All
     other traffic stays cleartext-forbidden. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
XML
echo "wrote $xmldir/network_security_config.xml"

# --- (2) backup rules -------------------------------------------------
# Android 12+ uses dataExtractionRules; older uses fullBackupContent.
# Include the whole app files domain (where settings.json lives) for both
# cloud backup and device-to-device transfer.
cat >"$xmldir/data_extraction_rules.xml" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<data-extraction-rules>
    <cloud-backup>
        <include domain="file" path="." />
    </cloud-backup>
    <device-transfer>
        <include domain="file" path="." />
    </device-transfer>
</data-extraction-rules>
XML
echo "wrote $xmldir/data_extraction_rules.xml"

cat >"$xmldir/backup_rules.xml" <<'XML'
<?xml version="1.0" encoding="utf-8"?>
<full-backup-content>
    <include domain="file" path="." />
</full-backup-content>
XML
echo "wrote $xmldir/backup_rules.xml"

# --- patch <application> attributes, idempotently ---------------------
python3 - "$manifest" <<'PY'
import re, sys
path = sys.argv[1]
src = open(path, encoding="utf-8").read()

wanted = {
    "android:networkSecurityConfig": "@xml/network_security_config",
    "android:allowBackup": "true",
    "android:fullBackupContent": "@xml/backup_rules",
    "android:dataExtractionRules": "@xml/data_extraction_rules",
}
inject = "".join(
    f' {k}="{v}"' for k, v in wanted.items() if k not in src
)
if not inject:
    print("manifest already patched — skipping")
else:
    new = re.sub(r"(<application\b)", r"\1" + inject, src, count=1)
    if new == src:
        sys.exit("::error::could not find <application> tag to patch")
    open(path, "w", encoding="utf-8").write(new)
    print("patched <application> with:" + inject)
PY

echo "android post-init patches applied"
